from fpdf import FPDF
from utils.helpers import format_inr_currency, format_percentage


def sanitize(text: str) -> str:
    """Helper to replace Rupee symbols and strip unsupported Unicode/Markdown characters for FPDF."""
    if not isinstance(text, str):
        text = str(text)
    text = text.replace("₹", "INR ")
    text = text.replace("**", "")  # Strip markdown bolding
    return text.encode("latin-1", "ignore").decode("latin-1")


def generate_pdf_report(symbol: str, company: dict, context: dict, ai_insight: str) -> bytes:
    """Generates a downloadable PDF report for a singular stock analysis."""
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)

    # Reset cursor position to left margin
    pdf.set_x(pdf.l_margin)

    # Render Title
    pdf.cell(
        0,
        10,
        sanitize(f"Financial Research Report: {company.get('name', symbol)} ({symbol})"),
        ln=True,
        align="C",
    )
    pdf.set_font("Helvetica", "I", 10)
    pdf.cell(0, 6, "Generated by Freaddy The Assistant", ln=True, align="C")
    pdf.ln(8)

    # 1. Fundamentals Section
    pdf.set_x(pdf.l_margin)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "1. Key Financial Fundamentals", ln=True)
    pdf.set_font("Helvetica", "", 10)

    fundamentals = [
        f"Current Price: {format_inr_currency(company.get('current_price'))}",
        f"52-Week High: {format_inr_currency(company.get('fifty_two_week_high'))}",
        f"52-Week Low: {format_inr_currency(company.get('fifty_two_week_low'))}",
        f"Market Cap: {format_inr_currency(company.get('market_cap'))}",
        f"Dividend Yield: {format_percentage(company.get('dividend_yield'))}",
        f"Sector: {company.get('sector', 'N/A')}",
        f"Industry: {company.get('industry', 'N/A')}",
    ]
    for line in fundamentals:
        pdf.set_x(pdf.l_margin)
        pdf.cell(0, 6, sanitize(f"  - {line}"), ln=True)
    pdf.ln(5)

    # 2. Technical Indicators
    pdf.set_x(pdf.l_margin)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "2. Technical Indicators Summary", ln=True)
    pdf.set_font("Helvetica", "", 10)

    sma_text = str(context.get("sma", "N/A"))
    ema_text = str(context.get("ema", "N/A"))

    pdf.set_x(pdf.l_margin)
    pdf.cell(0, 6, sanitize(f"  - SMA (20): {sma_text}"), ln=True)
    pdf.set_x(pdf.l_margin)
    pdf.cell(0, 6, sanitize(f"  - EMA (20): {ema_text}"), ln=True)
    pdf.set_x(pdf.l_margin)
    pdf.cell(
        0,
        6,
        sanitize(f"  - RSI (14): {context.get('rsi', 'N/A')} ({context.get('rsi_signal', 'Neutral')})"),
        ln=True,
    )
    pdf.ln(5)

    # 3. AI Insight
    pdf.set_x(pdf.l_margin)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "3. Gemini AI Strategic Insight", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(0, 6, sanitize(ai_insight) if ai_insight else "No insight available.")

    return bytes(pdf.output())


def generate_full_chat_pdf(messages: list) -> bytes:
    """Generates a downloadable PDF transcript of the entire chat session."""
    pdf = FPDF()
    pdf.add_page()
    
    # Transcript Title
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_x(pdf.l_margin)
    pdf.cell(0, 10, "Freaddy The Assistant - Chat Transcript", ln=True, align="C")
    pdf.ln(5)

    for msg in messages:
        role = msg.get("role")
        
        if role == "user":
            pdf.set_x(pdf.l_margin)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(37, 99, 235)  # Blue color for user
            pdf.multi_cell(0, 6, sanitize(f"You: {msg.get('content', '')}"))
            pdf.ln(2)
            
        elif role == "assistant":
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(0, 0, 0)  # Black color for AI
            msg_type = msg.get("type", "conversational")
            
            if msg_type == "error":
                pdf.set_x(pdf.l_margin)
                pdf.set_text_color(220, 38, 38)
                pdf.multi_cell(0, 6, sanitize(f"Error: {msg.get('content', '')}"))
                
            elif msg_type == "conversational":
                pdf.set_x(pdf.l_margin)
                pdf.multi_cell(0, 6, sanitize(f"Freaddy: {msg.get('content', '')}"))
                
            elif msg_type == "stock_analysis":
                symbol = msg.get("symbol", "Stock")
                company = msg.get("company", {})
                price = format_inr_currency(company.get("current_price"))
                mcap = format_inr_currency(company.get("market_cap"))
                
                pdf.set_x(pdf.l_margin)
                pdf.set_font("Helvetica", "B", 10)
                pdf.multi_cell(0, 6, sanitize(f"Freaddy Analysis: {company.get('name', symbol)} ({symbol})"))
                
                pdf.set_x(pdf.l_margin)
                pdf.set_font("Helvetica", "", 10)
                pdf.multi_cell(0, 6, sanitize(f"Current Price: {price} | Market Cap: {mcap}"))
                
                insight = msg.get("ai_insight", "")
                if insight:
                    pdf.ln(2)
                    pdf.set_x(pdf.l_margin)
                    pdf.multi_cell(0, 6, sanitize(f"AI Insight:\n{insight}"))
                    
            elif msg_type == "multi_comparison":
                pdf.set_x(pdf.l_margin)
                pdf.set_font("Helvetica", "B", 10)
                pdf.multi_cell(0, 6, sanitize("Freaddy Side-by-Side Comparison Matrix:"))
                pdf.set_font("Helvetica", "", 10)
                
                df = msg.get("dataframe")
                if df is not None and not df.empty:
                    for _, row in df.iterrows():
                        stock_name = row.get("Stock / Ticker", "N/A")
                        stk_price = row.get("Price (₹)", "N/A")
                        stk_pe = row.get("P/E Ratio", "N/A")
                        pdf.set_x(pdf.l_margin)
                        pdf.multi_cell(0, 6, sanitize(f"- {stock_name}: Price {stk_price} | P/E {stk_pe}"))
                
                insight = msg.get("ai_insight", "")
                if insight:
                    pdf.ln(2)
                    pdf.set_x(pdf.l_margin)
                    pdf.multi_cell(0, 6, sanitize(f"Comparative AI Insight:\n{insight}"))
            
            pdf.ln(6)
            pdf.set_text_color(0, 0, 0)
            
    return bytes(pdf.output())